info:
  app: 
    name: users-be
    
server:
    port: 30023
    
logging:
  level:
    com:
      cema: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
app:
  region: AR

spring:
  profiles:
    active: local
  application:
    name: users-be
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/users
    username: users
    password: m4_@96_+r2bF+Ad7

jwt:
  secret: cema

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.5:5432/users
  config:
    activate:
      on-profile: qa

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.6:5432/users
  config:
    activate:
      on-profile: prod
