info:
  app: 
    name: users-be
    
server:
    port: 30023
    ssl:
      key-store: classpath:cema.jks
      key-store-password: slipknot
      key-store-type: jks
      key-alias: proyecto-cema.com
      key-password: slipknot
    
logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
app:
  region: AR

spring:
  security:

    user:
      name: cema
      password: cema
      roles: user, admin
  profiles:
    active: local
  application:
    name: users-be
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/users
    username: users
    password: m4_@96_+r2bF+Ad7



---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.5:5432/users
  config:
    activate:
      on-profile: qa

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.6:5432/users
  config:
    activate:
      on-profile: prod
